### Loading the necessary packages

In [1]:
# import the classes and functions 
# of the pandas package
# refer to them henceforth as pd 
import pandas as pd
# numpy package
# pandas was built on numpy originally
import numpy as np
# matplotlib package
# visualisations (creating plots, graphs)
import matplotlib.pyplot as plt


from pathlib import Path

### Specifying the root directory path

In [2]:
# figuring out the current working directory (cwd)
# where is this file located
print(Path.cwd())

c:\Users\PC_DS_ECON_5\Desktop\data-analytics-python-example\notebooks

In [3]:
# specifying the path to the root directory 
# as text / string

# use forward slashes: /
# ROOT = 'c:/Users/PC_DS_ECON_5/Desktop/data-analytics-python-example'

# backslashes on Windows
ROOT = r'c:\Users\PC_DS_ECON_5\Desktop\data-analytics-python-example'

# optional:
# make it explicitly a path object
ROOT = Path(ROOT)
ROOT

WindowsPath('c:/Users/PC_DS_ECON_5/Desktop/data-analytics-python-example')

### Specifying the path of the directory where the data file is located

In [4]:
# with a Path object, it can be done simply with forward slash/es
DATA = ROOT / 'data'

In [5]:
DATA

WindowsPath('c:/Users/PC_DS_ECON_5/Desktop/data-analytics-python-example/data')

In [7]:
df = pd.read_parquet(DATA / 'nlsy97_emp_hed.parquet')

One can of course name objects freely. There is no rule that says that one needs to name a data frame `df`. The motivation here is to keep it short.

There is also the principle of being explicit. More explicit names are sometimes better.

In [ ]:
# displaying the list of column names
df.columns
# count the number of columns
# len() is length (for lists, tuples, dictionaries, it is unambiguous)
len(df.columns)

10

In [13]:
# number of rows and columns using shape attribute
df.shape
# number of rows
print(df.shape[0])
# number of columns
print(df.shape[1])

2556161
10

In most cases, there are multiple ways to do the same thing.

In [14]:
df

,person_id,year_month,college_status,emp_category,emp_weeklyhrs,year,gender,sample,ethnicity,birth_year_month
0,1,1995-10,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
1,1,1995-11,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
2,1,1995-12,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
3,1,1996-01,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
4,1,1996-02,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
...,...,...,...,...,...,...,...,...,...,...
2556156,9022,2023-06,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556157,9022,2023-07,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556158,9022,2023-08,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556159,9022,2023-09,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556160,9022,2023-10,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01

In [ ]:
# display the first seven rows head()
df.head(7)

,person_id,year_month,college_status,emp_category,emp_weeklyhrs,year,gender,sample,ethnicity,birth_year_month
0,1,1995-10,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
1,1,1995-11,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
2,1,1995-12,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
3,1,1996-01,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
4,1,1996-02,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
5,1,1996-03,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
6,1,1996-04,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09

In [16]:
# display the last five rows using tail()
df.tail(5)

,person_id,year_month,college_status,emp_category,emp_weeklyhrs,year,gender,sample,ethnicity,birth_year_month
2556156,9022,2023-06,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556157,9022,2023-07,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556158,9022,2023-08,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556159,9022,2023-09,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556160,9022,2023-10,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01

With the `value_counts()` method, one can compute 

 - frequencies (number of occurrences) 
 - and relative frequencies (proportions)

for distinct values / value-combinations of variables

for a single variable: how often a particular value occurs

for multiple variables: how often a particular combination of values occurs

In [ ]:
# frequencies / number observations for each value
# one way
df['year'].value_counts(
    normalize=False
)
# another way
df.value_counts(
    subset=['year'],
    normalize=False
)

pandas.Series

In [ ]:
# at this point the resulting object is a single column 
# (Series in pandas teminology)
type(
    df.value_counts(
        subset=['year'],
        normalize=False
    )   
)

# with the values in the column being the frequencies / number of occurrences
# and the index (on the left) being the distinct values of the variable

In [22]:
# to make the index into a column
# reset_index() --> make the index into a column 
df.value_counts(
    subset=['year'],
    normalize=False
).reset_index()

    year   count
0   2002  103472
1   2003  102620
2   2001  102433
3   2004  101987
4   2005  101495
5   2006  101015
6   2007  100367
7   2008   99724
8   2009   99356
9   2010   98610
10  2000   98537
11  2011   97644
12  2012   95773
13  2013   95686
14  2014   94151
15  2015   93907
16  2016   91425
17  2017   91198
18  1999   90422
19  2018   89379
20  2019   88948
21  2020   84972
22  2021   84246
23  2022   79394
24  1998   75550
25  2023   68187
26  1997   56859
27  1996   36451
28  1995   20747
29  1994    6419
30  2024    5187

`.loc` for subsetting the data frame and conditional modification of entries

In [23]:
#df['year_month']
# if there is no space or some other special character in the name
df.year_month

0          1995-10
1          1995-11
2          1995-12
3          1996-01
4          1996-02
            ...
2556156    2023-06
2556157    2023-07
2556158    2023-08
2556159    2023-09
2556160    2023-10
Name: year_month, Length: 2556161, dtype: period[M]

In [ ]:
# testing elementwise whether the entry/value is equal to '2009-06' 
# we obtain a column with True and False values / Yes or No /
df['year_month'].eq('2009-06')
df.year_month.eq('2009-06')
# using sum() it is possible to count the number of observations/rows
# for which the condition (equality with '2009-06') holds
df['year_month'].eq('2009-06').sum()
# because False is equivalent to 0 (zero)
# and True is equivalent to 1 (one)

np.int64(8279)

In [ ]:
# selection of observations / rows 
# such that the year_month == June 2009
# saving it as df_june09
df_june09 = df.loc[df['year_month'].eq('2009-06'),:].copy()
# to get relative frequencies: normalize=True
# computing the relative frequencies
rel_freq = (
    df_june09['emp_category']
        .value_counts(
            normalize=True
        )
)
# relative frequencies should sum to 1
# proportions / shares of observations
import math
math.isclose(rel_freq.sum(),1)

True

In [ ]:
# setting dropna=False
# the (relative) frequencies of missing values will be computed as well
rel_freq = (
    df_june09
        .value_counts(
            subset=['emp_category'],
            normalize=True,
            dropna=False
        )
)
# not a good example because there is no missing value
# df_june09['emp_category'].isna().sum()
# but if there were missing values, 
# they would be treated as a separate category

np.int64(0)

The share of observations classified as unemployed does not correspond to the official unemployment rate. For at least two reasons:
 - Specific sample of individuals born between 1980 and 1984
 - Usually unemployment rate is usually computed as:
 $$ \frac{\text{number of unemployed}}{\text{number of unemployed} + \text{number of employed}} $$
 (Response to a question: this LATEX Math mode with the dollar $$ signs)

### Unit of observation

What does each row describe?
 - Does each row describe a separate / distinct person?
 - Does each row correspond to information on a person in a given year?
 - Does each row correspond to information on a person in a given month?

In [35]:
df

,person_id,year_month,college_status,emp_category,emp_weeklyhrs,year,gender,sample,ethnicity,birth_year_month
0,1,1995-10,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
1,1,1995-11,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
2,1,1995-12,<NA>,non-participant,<NA>,1995,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
3,1,1996-01,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
4,1,1996-02,<NA>,unemployed,<NA>,1996,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
...,...,...,...,...,...,...,...,...,...,...
2556156,9022,2023-06,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556157,9022,2023-07,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556158,9022,2023-08,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556159,9022,2023-09,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556160,9022,2023-10,Enrolled in Graduate program,employed,40.0,2023,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01

Based on visual inspection, it seems to be the case that the unit of observation is `person_id` X `year_month`. According to this hypothesis: each observation would contain information on a given individual in a given month.

How can we test that this happens to be the case?
How can we test that the combination of `person_id` and `year_month` uniquely identifies observations/rows?

In [36]:
# ruling out technical duplicates 
# in order not to have exactly the same column twice
# let us just use drop_duplicates()
# this will make sure that if two rows are fully identical
# then only one is kept
df = df.drop_duplicates()

In [ ]:
# using value_counts() to test 
# whether a specific combination of variables
# uniquely identifies the observations

In [ ]:
# let us first count the number observations
# per combination of person_id and year_month
df.value_counts(
    subset=['person_id', 'year_month']
).reset_index()
# for each pair of person_id X year_month
# count corresponds to the number of observations

         person_id year_month  count
0                1    1995-10      1
1                1    1995-11      1
2                1    1995-12      1
3                1    1996-01      1
4                1    1996-02      1
...            ...        ...    ...
2556156       9022    2023-06      1
2556157       9022    2023-07      1
2556158       9022    2023-08      1
2556159       9022    2023-09      1
2556160       9022    2023-10      1

[2556161 rows x 3 columns]

In [38]:
# let us count how many times 
# a person_id X year_month pair occurs once, twice, three times etc
# simply call a second value_counts() 
# on the frequencies / number of occurrences
(
    df
        .value_counts(
            subset=['person_id', 'year_month']
            )
        .reset_index()
        .value_counts(
            subset=['count']
        )
)

count
1        2556161
Name: count, dtype: int64

In [39]:

# person_id and year do not uniquely identify observations
(
    df
        .value_counts(
            subset=['person_id', 'year']
            )
        .reset_index()
        .value_counts(
            subset=['count']
        )
)

count
12       199843
10         4224
11         3030
9          2961
1          2852
3          2168
2          2109
4          1675
5          1448
8          1369
7          1346
6          1323
Name: count, dtype: int64

Unit of observation

On what units / at which level the dataset contains information

Is it at the individual level, at the individual-time period level (i.e. repeated cross-section or panel data?, if yes, at what frequency)

unit of observation is not just a mathematical concept
 - of course we wish to make sure that the particular combination of variables (identifiers, time variables) uniquely identifies the observations
 - but the variables need to make sense

### Employment patterns around major events

In [40]:
df2 = df.copy()

In [ ]:
# between is inclusive: both bounds are included
# adding another condition: & for 'and' and | for 'or'
# this is pandas specific meaning of & and |
# in Python: and, or

# reset_index(drop=True) because only specific/a subset of rows are kept
# this is optional
df2 = df2.loc[df2['year'].between(left=2019,right=2020) &
        df2['sample'].eq('Cross-sectional'),:].reset_index(drop=True)

In [41]:
df2.loc[df2['year'].between(left=2019,right=2020) &
        df2['sample'].eq('Cross-sectional'),:]

,person_id,year_month,college_status,emp_category,emp_weeklyhrs,year,gender,sample,ethnicity,birth_year_month
277,1,2019-01,Not enrolled in college,unemployed,<NA>,2019,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
278,1,2019-02,Not enrolled in college,unemployed,<NA>,2019,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
279,1,2019-03,Not enrolled in college,unemployed,<NA>,2019,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
280,1,2019-04,Not enrolled in college,unemployed,<NA>,2019,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
281,1,2019-05,Not enrolled in college,unemployed,<NA>,2019,Female,Cross-sectional,Non-Black / Non-Hispanic,1981-09
...,...,...,...,...,...,...,...,...,...,...
2556122,9022,2020-08,Not enrolled in college,employed,40.0,2020,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556123,9022,2020-09,Not enrolled in college,employed,40.0,2020,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556124,9022,2020-10,Not enrolled in college,employed,40.0,2020,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556125,9022,2020-11,Not enrolled in college,employed,40.0,2020,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01
2556126,9022,2020-12,Not enrolled in college,employed,40.0,2020,Female,Cross-sectional,Non-Black / Non-Hispanic,1982-01