In [1]:
import pandas as pd

##### Lists and Tuples
After creating the object
 - you can modify a list
 - you cannot modify a tuple

In [2]:
# creating a list with information on an economist
an_economist = ['Joan Robinson', 1903] 
print(an_economist)

['Joan Robinson', 1903]

In [3]:
# year of death
an_economist.append(1983)
# country of birth
an_economist.append('UK')
# nobel_prize_year
an_economist.append(1975)

In [4]:
an_economist

['Joan Robinson', 1903, 1983, 'UK', 1975]

Lists can be changed after creation

In [5]:
# indexing in Python starts with 0
# in contrast to R (in R, indexing starts with 1)
an_economist[4] = False

In [6]:
an_economist

['Joan Robinson', 1903, 1983, 'UK', False]

Tuple with information on another economist

In [7]:
another_economist = 'Ragnar Frisch', 1895, 1973, 'Norway', 1969
another_economist

('Ragnar Frisch', 1895, 1973, 'Norway', 1969)

In [8]:
# elements of a tuple cannot be changed after creation
another_economist[0] = 'Ragnar Anton Kittil Frisch'

TypeError: 'tuple' object does not support item assignment

In [9]:
# converting 
# a list (here the one containing information on Joan Robinson) 
# to a tuple
an_economist = tuple(an_economist)

In [10]:
# checking the type of our object 
type(an_economist)

tuple

Looking for a data structure or type of object with the type of information (the variable) for which the values are being stored

# Dictionaries

unambiguous assignment of *values* to *keys*
each *key* occurs only once

In [11]:
# creating a dictionary 
# with information on yet another economist 
# [] lists, () tuples, {} dicts or sets
# empty dictionary
yet_another_economist = {}


# each key occurs only once
# a value is assigned to each key

# adding items to the dictionary
yet_another_economist['name'] = 'John Maynard Keynes'
yet_another_economist['year_of_birth'] = 1883
yet_another_economist['year_of_death'] = 1946
yet_another_economist['country_of_birth'] = 'UK'
yet_another_economist['nobel_prize_year'] = False

yet_another_economist

{'name': 'John Maynard Keynes',
 'year_of_birth': 1883,
 'year_of_death': 1946,
 'country_of_birth': 'UK',
 'nobel_prize_year': False}

Other ways of adding items to / specifying items of dictionaries:

In [12]:
the_fourth_economist = {
    'name': 'Jan Tinbergen',
    'year_of_birth': 1903,
    'year_of_death' : 1994,
    'country_of_birth': 'Netherlands',
    'nobel_prize_year': 1969
}

In [13]:
# using the function dict() 
# with a list of tuples as the input/argument 




the_fifth_economist = dict([
    ('name', 'Elinor Ostrom'),
    ('year_of_birth', 1933),
    ('year_of_death', 2012),
    ('country_of_birth', 'USA'),
    ('nobel_prize_year', 2009)
])
the_fifth_economist

{'name': 'Elinor Ostrom',
 'year_of_birth': 1933,
 'year_of_death': 2012,
 'country_of_birth': 'USA',
 'nobel_prize_year': 2009}

In [14]:
print(type(an_economist))
print(type(another_economist))
print(type(yet_another_economist))
print(type(the_fourth_economist))
print(type(the_fifth_economist))

<class 'tuple'>
<class 'tuple'>
<class 'dict'>
<class 'dict'>
<class 'dict'>

In [15]:
an_economist

('Joan Robinson', 1903, 1983, 'UK', False)

In [16]:
# collecting the keys / variable names here
attribute_names = list(yet_another_economist.keys())

In [17]:
# creating a list of tuples
# pairing the attribute/variable names with the corresponding values
list(zip(attribute_names, an_economist))
# this can directly be converted to a dictionary
an_economist = dict(list(zip(attribute_names, an_economist)))

In [18]:
an_economist

{'name': 'Joan Robinson',
 'year_of_birth': 1903,
 'year_of_death': 1983,
 'country_of_birth': 'UK',
 'nobel_prize_year': False}

In [19]:
# converting the other tuple to a dictionary
another_economist = dict(list(zip(attribute_names, another_economist)))

In [20]:
another_economist

{'name': 'Ragnar Frisch',
 'year_of_birth': 1895,
 'year_of_death': 1973,
 'country_of_birth': 'Norway',
 'nobel_prize_year': 1969}

In [21]:
print(type(an_economist))
print(type(another_economist))
print(type(yet_another_economist))
print(type(the_fourth_economist))
print(type(the_fifth_economist))

<class 'dict'>
<class 'dict'>
<class 'dict'>
<class 'dict'>
<class 'dict'>

In [22]:
# creating a list with all the dictionaries
some_economists = [an_economist, 
                   another_economist, 
                   yet_another_economist,
                   the_fourth_economist,
                   the_fifth_economist]

## Functions and using `input()`
- enter data on economists using `input()` embedded in a function

In [23]:
# string, more or less text / sequence of characters 
a_string = 'Esther Duflo'
# putting together strings
a_string = a_string + ' was born in 1972.'

a_string

'Esther Duflo was born in 1972.'

In [24]:
# creating the function add_economist()
def add_economist():
    # collect the value for each attribute
    # keeping the five attributes
    attribute_names = ('name', 
                       'year_of_birth', 
                       'year_of_death', 
                       'country_of_birth',
                       'nobel_prize_year')
    # empty dictionary
    # new_economist exists only within the function
    new_economist = {}
    # looping over attributes
    # for loop
    for attribute_name in attribute_names:
        # adding an element to the dictionary attribute_dict
        # with key/attribute name /variable name 
        # corresponding to the content of attribute_name 
        new_economist[attribute_name] = input(attribute_name + ': ')
    # at this point (after the for loop), we have the dictionary 
    # filled with the attribute names and values    
    # now, let us add it to the list of dictionaries we already have
    # some_economists exists outside (it was created outside)
    some_economists.append(new_economist)

In [25]:
add_economist()

In [26]:
some_economists[5]

{'name': 'Trygve Haavelmo',
 'year_of_birth': '1911',
 'year_of_death': '1999',
 'country_of_birth': 'Norway',
 'nobel_prize_year': '1989'}

## Using classes of objects

In [27]:
class Economist:
    # initialiser function
    # to create objects of this class
    # self (convention) --> refers to the object itself
    def __init__(self):
        # five attributes
        # each at baseline / by default set to None (unknown)
        self.name = None 
        self.year_of_birth = None
        self.year_of_death = None
        self.countr_of_birth = None
        self.nobel_prize_year = None

In [28]:
# how many economists we already have
# put differently, how many items are in our list
len(some_economists)

6

In [29]:
# creating an economist with default attributes
# defined in the __init__()
the_seventh_economist = Economist()

In [30]:
the_seventh_economist.name = 'Esther Duflo'

In [31]:
# specifying/modifying more attributes
the_seventh_economist.year_of_birth = 1972
the_seventh_economist.countr_of_birth = 'France'
the_seventh_economist.nobel_prize_year = 2019

In [32]:
the_seventh_economist.__dict__

{'name': 'Esther Duflo',
 'year_of_birth': 1972,
 'year_of_death': None,
 'countr_of_birth': 'France',
 'nobel_prize_year': 2019}

In [33]:
class Economist:
    # initialiser function
    # to create objects of this class
    # self (convention) --> refers to the object itself
    def __init__(self):
        # five attributes
        # each at baseline / by default set to None (unknown)
        self.name = None 
        self.year_of_birth = None
        self.year_of_death = None
        self.countr_of_birth = None
        self.nobel_prize_year = None
    # add_attributes()
    # setting the attributes interactively using input()
    # function belonging to objects of the Economist class
    # jargon: called a "method" of the Economist class
    def add_attributes(self):
        # retrieve the attribute names
        # these are the keys in the __dict__ of the object itself
        attribute_names = self.__dict__.keys()
        # for each attribute name, let the user enter the corresponding value 
        # interactively using input()
        for attribute_name in attribute_names:
            attribute_value = input(attribute_name + ': ')
            # here, let us use the setattr() function
            setattr(self, attribute_name, attribute_value)

In [34]:
another_living_economist = Economist()

In [35]:
another_living_economist.add_attributes()

In [36]:
another_living_economist.__dict__

{'name': 'Amartya Sen',
 'year_of_birth': '1933',
 'year_of_death': 'False',
 'countr_of_birth': 'India',
 'nobel_prize_year': '1998'}

In [37]:
# adding the seventh and eighth economists to our list
some_economists.append(the_seventh_economist)
some_economists.append(another_living_economist)

In [38]:
# removing the last two elements, because I added the object, 
# and not just the dictionary of attributes 
some_economists.pop()
some_economists.pop()

In [39]:
# adding only the dictionary of attributes each time
some_economists.append(the_seventh_economist.__dict__)
some_economists.append(another_living_economist.__dict__)

In [40]:
some_economists

[{'name': 'Joan Robinson',
  'year_of_birth': 1903,
  'year_of_death': 1983,
  'country_of_birth': 'UK',
  'nobel_prize_year': False},
 {'name': 'Ragnar Frisch',
  'year_of_birth': 1895,
  'year_of_death': 1973,
  'country_of_birth': 'Norway',
  'nobel_prize_year': 1969},
 {'name': 'John Maynard Keynes',
  'year_of_birth': 1883,
  'year_of_death': 1946,
  'country_of_birth': 'UK',
  'nobel_prize_year': False},
 {'name': 'Jan Tinbergen',
  'year_of_birth': 1903,
  'year_of_death': 1994,
  'country_of_birth': 'Netherlands',
  'nobel_prize_year': 1969},
 {'name': 'Elinor Ostrom',
  'year_of_birth': 1933,
  'year_of_death': 2012,
  'country_of_birth': 'USA',
  'nobel_prize_year': 2009},
 {'name': 'Trygve Haavelmo',
  'year_of_birth': '1911',
  'year_of_death': '1999',
  'country_of_birth': 'Norway',
  'nobel_prize_year': '1989'},
 {'name': 'Esther Duflo',
  'year_of_birth': 1972,
  'year_of_death': None,
  'countr_of_birth': 'France',
  'nobel_prize_year': 2019},
 {'name': 'Amartya Sen',
  'year_of_birth': '1933',
  'year_of_death': 'False',
  'countr_of_birth': 'India',
  'nobel_prize_year': '1998'}]

In [41]:
class Economist:
    # initialiser function
    # to create objects of this class
    # self (convention) --> refers to the object itself
    def __init__(self, 
                 name = None, 
                 year_of_birth = None, 
                 year_of_death = None, 
                 country_of_birth = None,
                 nobel_prize_year = None):
        # five attributes
        # each at baseline / by default set to None (unknown)
        self.name = name
        self.year_of_birth = year_of_birth
        self.year_of_death = year_of_death
        self.country_of_birth = country_of_birth
        self.nobel_prize_year = nobel_prize_year

In [42]:
the_ninth_economist = Economist(name='Reinhard Selten', 
                                year_of_birth=1930,
                                year_of_death=2016,
                                country_of_birth='Germany',
                                nobel_prize_year=1994)

In [43]:
the_ninth_economist.__dict__

{'name': 'Reinhard Selten',
 'year_of_birth': 1930,
 'year_of_death': 2016,
 'country_of_birth': 'Germany',
 'nobel_prize_year': 1994}

In [44]:
some_economists.append(the_ninth_economist.__dict__)

In [45]:
# length / number of items
len(some_economists)

9

In [46]:
some_economists

[{'name': 'Joan Robinson',
  'year_of_birth': 1903,
  'year_of_death': 1983,
  'country_of_birth': 'UK',
  'nobel_prize_year': False},
 {'name': 'Ragnar Frisch',
  'year_of_birth': 1895,
  'year_of_death': 1973,
  'country_of_birth': 'Norway',
  'nobel_prize_year': 1969},
 {'name': 'John Maynard Keynes',
  'year_of_birth': 1883,
  'year_of_death': 1946,
  'country_of_birth': 'UK',
  'nobel_prize_year': False},
 {'name': 'Jan Tinbergen',
  'year_of_birth': 1903,
  'year_of_death': 1994,
  'country_of_birth': 'Netherlands',
  'nobel_prize_year': 1969},
 {'name': 'Elinor Ostrom',
  'year_of_birth': 1933,
  'year_of_death': 2012,
  'country_of_birth': 'USA',
  'nobel_prize_year': 2009},
 {'name': 'Trygve Haavelmo',
  'year_of_birth': '1911',
  'year_of_death': '1999',
  'country_of_birth': 'Norway',
  'nobel_prize_year': '1989'},
 {'name': 'Esther Duflo',
  'year_of_birth': 1972,
  'year_of_death': None,
  'countr_of_birth': 'France',
  'nobel_prize_year': 2019},
 {'name': 'Amartya Sen',
  'year_of_birth': '1933',
  'year_of_death': 'False',
  'countr_of_birth': 'India',
  'nobel_prize_year': '1998'},
 {'name': 'Reinhard Selten',
  'year_of_birth': 1930,
  'year_of_death': 2016,
  'country_of_birth': 'Germany',
  'nobel_prize_year': 1994}]

## Using pandas

 - working with data in tabular form
 - pandas DataFrames

 - list of dictionaries (keys/attribute names are the variable names) is easy to convert to a pandas DataFrame

In [76]:
# convention to abbreviate pandas as pd
import pandas as pd 
# converting list of dictionaries to pandas dataframe
some_economists_df = pd.DataFrame(some_economists)

In [78]:
some_economists_df.columns

Index(['name', 'year_of_birth', 'year_of_death', 'country_of_birth',
       'nobel_prize_year', 'countr_of_birth'],
      dtype='str')

Ways to store/organise data
- Lists, Tuples, Dictionaries
- Functions
- Object Classes

Example: artificial small dataset on economists
List of dictionaries
Each dictionary contained information on a given economist

List of Dictionaries
Easily convertible to a pandas DataFrame
which provides a more natural representation of data
in tabular form

In [47]:
import pandas as pd

In [48]:
some_economists_df = pd.DataFrame(some_economists)

In [ ]:
# columns/variables
# .columns attribute 
# of the dataframe some_economists_df
some_economists_df.columns

Index(['name', 'year_of_birth', 'year_of_death', 'country_of_birth',
       'nobel_prize_year', 'countr_of_birth'],
      dtype='str')

In [ ]:
# .head() method/function
# belonging to the (class of) object some_economists_df
# displaying the first 5 rows/observations 
# of the dataset
some_economists_df.head(5)

,name,year_of_birth,year_of_death,country_of_birth,nobel_prize_year,countr_of_birth
0,Joan Robinson,1903,1983,UK,False,NaN
1,Ragnar Frisch,1895,1973,Norway,1969,NaN
2,John Maynard Keynes,1883,1946,UK,False,NaN
3,Jan Tinbergen,1903,1994,Netherlands,1969,NaN
4,Elinor Ostrom,1933,2012,USA,2009,NaN

In [52]:
some_economists_df.tail(5)

,name,year_of_birth,year_of_death,country_of_birth,nobel_prize_year,countr_of_birth
4,Elinor Ostrom,1933,2012,USA,2009,NaN
5,Trygve Haavelmo,1911,1999,Norway,1989,NaN
6,Esther Duflo,1972,None,NaN,2019,France
7,Amartya Sen,1933,False,NaN,1998,India
8,Reinhard Selten,1930,2016,Germany,1994,NaN

Correcting the problem of having two columns for the same variable because of the typo

In [55]:
# list of selected columns
selected_columns = ['country_of_birth', 
                    'countr_of_birth']
some_economists_df[selected_columns]

  country_of_birth countr_of_birth
0               UK             NaN
1           Norway             NaN
2               UK             NaN
3      Netherlands             NaN
4              USA             NaN
5           Norway             NaN
6              NaN          France
7              NaN           India
8          Germany             NaN

`.loc` selector

In [56]:
row_conditions = (
    some_economists_df['country_of_birth'].isna()
)
row_conditions

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8    False
Name: country_of_birth, dtype: bool

In [58]:
df = some_economists_df.copy()

In [61]:
df.loc[row_conditions, 
       'country_of_birth'] = df.loc[row_conditions, 
                                    'countr_of_birth']
df

,name,year_of_birth,year_of_death,country_of_birth,nobel_prize_year,countr_of_birth
0,Joan Robinson,1903,1983,UK,False,NaN
1,Ragnar Frisch,1895,1973,Norway,1969,NaN
2,John Maynard Keynes,1883,1946,UK,False,NaN
3,Jan Tinbergen,1903,1994,Netherlands,1969,NaN
4,Elinor Ostrom,1933,2012,USA,2009,NaN
5,Trygve Haavelmo,1911,1999,Norway,1989,NaN
6,Esther Duflo,1972,None,France,2019,France
7,Amartya Sen,1933,False,India,1998,India
8,Reinhard Selten,1930,2016,Germany,1994,NaN

In [63]:
df['country_of_birth'].isna().sum()

np.int64(0)

In [65]:
df = df.drop(columns=['countr_of_birth'])
df.columns

Index(['name', 'year_of_birth', 'year_of_death', 'country_of_birth',
       'nobel_prize_year'],
      dtype='str')

In [66]:
df

,name,year_of_birth,year_of_death,country_of_birth,nobel_prize_year
0,Joan Robinson,1903,1983,UK,False
1,Ragnar Frisch,1895,1973,Norway,1969
2,John Maynard Keynes,1883,1946,UK,False
3,Jan Tinbergen,1903,1994,Netherlands,1969
4,Elinor Ostrom,1933,2012,USA,2009
5,Trygve Haavelmo,1911,1999,Norway,1989
6,Esther Duflo,1972,None,France,2019
7,Amartya Sen,1933,False,India,1998
8,Reinhard Selten,1930,2016,Germany,1994

Missing values and data types in pandas

In [67]:
# dtypes attribute
# data types of the columns
df.dtypes

name                   str
year_of_birth       object
year_of_death       object
country_of_birth       str
nobel_prize_year    object
dtype: object

*str* = string (sequence of characters / text / qualitative)

need to address the problem causing *object* data type
in all of the cases here, the columns with object data type should be numerical / quantitative (with eventually values)

Instead of 'None' and 'False', let us have explicitly missing values `pd.NA`

In [ ]:
# selecting rows with NA
rows_with_NA = (
    df['year_of_death'].isin([None, False])
)
# changing the values to explicit NA values
df.loc[rows_with_NA, 'year_of_death'] = pd.NA

# selecting rows with NA
rows_with_NA = (
    df['nobel_prize_year'].isin([None, False])
)
# changing the values to explicit NA values
df.loc[rows_with_NA, 'nobel_prize_year'] = pd.NA

In [74]:
df

,name,year_of_birth,year_of_death,country_of_birth,nobel_prize_year
0,Joan Robinson,1903,1983,UK,<NA>
1,Ragnar Frisch,1895,1973,Norway,1969
2,John Maynard Keynes,1883,1946,UK,<NA>
3,Jan Tinbergen,1903,1994,Netherlands,1969
4,Elinor Ostrom,1933,2012,USA,2009
5,Trygve Haavelmo,1911,1999,Norway,1989
6,Esther Duflo,1972,<NA>,France,2019
7,Amartya Sen,1933,<NA>,India,1998
8,Reinhard Selten,1930,2016,Germany,1994

In [77]:
# convert the data types 
# to pandas dtypes
df.convert_dtypes()
df.dtypes

name                   str
year_of_birth       object
year_of_death       object
country_of_birth       str
nobel_prize_year    object
dtype: object

in every column containing years
the values are either integer (whole number) or missing

In [78]:
# setting the datatype of a column to integer 
df['year_of_birth'] = df['year_of_birth'].astype(int)
df.dtypes

name                   str
year_of_birth        int64
year_of_death       object
country_of_birth       str
nobel_prize_year    object
dtype: object

In [ ]:
# converting data type to integer
df['year_of_death'] = (
    df['year_of_death'].astype(str).astype('Int64')
)
df.convert_dtypes()
df.dtypes

name                   str
year_of_birth        int64
year_of_death        Int64
country_of_birth       str
nobel_prize_year    object
dtype: object

In [ ]:
# first convert to a string
# convert it to an integer that allows for missing values
df['nobel_prize_year'] = (
    df['nobel_prize_year']
        .astype(str)
        .astype('Int64')
)
df.convert_dtypes()
df.dtypes

name                  str
year_of_birth       int64
year_of_death       Int64
country_of_birth      str
nobel_prize_year    Int64
dtype: object

In [88]:
df.dtypes

name                  str
year_of_birth       int64
year_of_death       Int64
country_of_birth      str
nobel_prize_year    Int64
dtype: object